pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
metadata:
  labels:
    component: ci
spec: 
  containers:
  - name: docker
    image: docker:24.0.5
    command: ["cat"]
    tty: true
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock

  - name: jnlp
    image: jenkins/inbound-agent:latest
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
'''
        }
    }
    
    environment {
        DOCKER_IMAGE = "navin1199/frontend-service"
        DOCKER_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'master', url: 'https://github.com/Navin470/E-Commerce-Platform.git'
            }
        }

        stage('Build Frontend Image') {
            steps {
                container("docker"){
                    sh "docker build -t $DOCKER_IMAGE:$DOCKER_TAG frontend"
                }
            }
        }

        stage('Login to DockerHub') {
            steps {
                container("docker"){
                    withCredentials([usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'USERNAME',
                        passwordVariable: 'PASSWORD'
                    )]) {
                        sh "echo \$PASSWORD | docker login -u \$USERNAME --password-stdin"
                    }
                }
            }
        }

        stage('Push Frontend Image') {
            steps {
                container("docker"){
                    sh "docker push $DOCKER_IMAGE:$DOCKER_TAG"
                }
            }
        }

        stage('Cleanup') {
            steps {
                container("docker"){
                    sh "docker rmi $DOCKER_IMAGE:$DOCKER_TAG || true"
                }
            }
        }
    }

    post {
        success {
            echo "Frontend Service Build & Push Successful"
        }
        failure {
            echo "Frontend Build Failed"
        }
    }
}