apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-frontend
  # ArgoCD usually lives in the 'argocd' namespace
  namespace: argocd
spec:
  project: default # The project group this app belongs to
  source:
    # 1. Where your code lives
    repoURL: 'https://github.com/Navin470/E-Commerce-Platform.git'
    targetRevision: HEAD
    # 2. The folder inside the repo containing your K8s manifests (Deployment/Service)
    path: k8s/infra-frontend

  destination:
    # 3. Where to deploy the app
    server: 'https://kubernetes.default.svc'
    # The namespace where your frontend should run
    namespace: ecommerce

  # 4. How ArgoCD should behave when code changes
  syncPolicy:
    automated:
      prune: true      # Delete resources that are removed from Git
      selfHeal: true   # If someone manually edits K8s, ArgoCD will change it back
    syncOptions:
    - CreateNamespace=true # Create 'ecommerce-prod' if it doesn't exist