apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: ecommerce
data:
  NODE_ENV: "production"
  PORT: "3002"
  # Updated from MongoDB to Postgres
  POSTGRES_URL: "postgresql://user:password@postgres-service:5432/auth_db"