apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: ecommerce
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path  # <--- Add this exact name from your 'kubectl get sc'
  resources:
    requests:
      storage: 1Gi