apiVersion: v1
kind: Service
metadata:
  name: auth-db            # This MUST match the host in your DATABASE_URL
  namespace: ecommerce
  annotations:
    # Service should be ready when the DB deployment starts
    argocd.argoproj.io/sync-wave: "-1"
spec:
  selector:
    app: auth-db           # This MUST match the labels in postgres-deploy.yaml
  ports:
    - protocol: TCP
      port: 5432           # The port your App will connect to
      targetPort: 5432     # The port Postgres is listening on inside the container
  type: ClusterIP          # Internal only (Security Best Practice)