apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: ecommerce
type: Opaque
data:
  # Values must be Base64 encoded
  # 'admin' in base64 is YWRtaW4=
  # 'password123' in base64 is cGFzc3dvcmQxMjM=
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM=
  JWT_SECRET: bXktc3VwZXItc2VjcmV0LWtleS1oZXJl