apiVersion: v1
kind: Secret
metadata:
  name: admin-service-secrets
  namespace: ecommerce
type: Opaque
data:
  # Values must be Base64 encoded
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  JWT_SECRET: c3VwZXItc2VjcmV0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==