apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-db
  namespace: ecommerce
  labels:
    app: admin-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-db
  template:
    metadata:
      labels:
        app: admin-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
          # This name MUST match what you use in your app's DATABASE_URL
          - name: POSTGRES_DB
            value: "admin_db"
          
          # Pulling credentials from your existing Secret
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: admin-service-secrets
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: admin-service-secrets
                key: POSTGRES_PASSWORD
          # - name: POSTGRES_USER
          #   value: postgres
          # - name: POSTGRES_PASSWORD
          #   value: postgres
        
        # Resources to prevent the DB from consuming all node memory
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"

        # Where the actual data lives inside the container
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-admin