apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-admin
  namespace: ecommerce
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi